
add_SE: true
alpha: 0.5
aug_add: 0.9
batch_size: 10240
dataset: gender
device: cuda:0
dropout: 0.0
edge_drop: 0.99
epochs: 1000
eval_step: 5
gamma: 9.0
hid_dim: 512
in_drop: 0.3
info_loss_weight: 0.9
k: 10
log_dir: ./log/
loss: focal
loss_weight: null
lr: 0.0005
max_epochs: 500
model_name: HGT
n_data: 0
n_gnn: 3
n_mlp: 3
num_neigh: 10
num_train_per_class: 10
out_dim: 64
patient: 5
res_layer: false
se_min_count: 100
seed: 42
show_training: false
shuffle_attr: true
split: random
temperature: 0.09
use_jk: true
use_scheduler: false
weight_decay: 5.0e-05
